// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fixed Orca pane identity that may be sent over authenticated local daemon IPC.
 */
export type HookOwner = { paneKey: string, tabId: string | null, worktreeId: string | null, launchToken: string | null, hookEndpointPath: string, };
